## Documentation: http://docs.travis-ci.com/user/languages/julia/
branches:
  only:
  - master

language: julia
os:
  - linux
dist:
  - bionic
julia:
  - 1.7.2
env:
  - PYTHON=~/.julia/conda/3/bin/python
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f protosyn.yml
  - source $(conda info --root)/etc/profile.d/conda.sh
  - conda activate protosyn
  - which python
  - python -c "import torchani; torchani.models.ANI2x()"
  - julia -e 'using Pkg; Pkg.add.(["PyCall"]);Pkg.build("PyCall");using PyCall;println("Python for Julia $(PyCall.python) ver. $(PyCall.pyversion)")'
notifications:
  email: false
git:
  depth: 99999999
jobs:
  include:
    - stage: "Documentation"
      julia: 1.7.2
      os: linux
      script:
        # - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter"); Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        # - julia --project=docs/ docs/make.jl
        - julia docs/make.jl
      after_success: skip
