## Documentation: http://docs.travis-ci.com/user/languages/julia/
branches:
  only:
  - master
  - refactoring

language: julia
os:
  - linux
julia:
  - 1.6.1
notifications:
  email: false
git:
  depth: 99999999
jobs:
  include:
    - stage: "Documentation"
      julia: 1.6.1
      os: linux
      script:
        - pip install torch
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter"); Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
